In [5]:
import matplotlib.pyplot as plt
import numpy as np

In [3]:
fig = plt.figure()
fig.subplots_adjust(hspace=0.8, wspace=0.6)
for i in range(1, 8):
    ax = fig.add_subplot(2, 4, i)
    ax.text(0.5, 0.5, str((2, i, 3)), fontsize=12, ha='center' )

In [7]:
distribution1 = np.random.normal(0.1, 3, 2000)
distribution2 = np.random.normal(-2, 1, 2000)
distribution3 = np.random.normal(3, 2, 2000)
distribution4 = np.random.normal(7, 2, 2000)

kwargs = dict(histtype='stepfilled', alpha=0.3, normed=True, bins=40)
plt.hist(distribution1, **kwargs)
# plt.hist(distribution2, **kwargs)
# plt.hist(distribution3, **kwargs)
# plt.hist(distribution4, **kwargs)

(array([0.00082853, 0.00082853, 0.00165705, 0.0033141 , 0.00248558,
        0.00497115, 0.00994231, 0.01574199, 0.01242788, 0.0422548 ,
        0.04639743, 0.05716826, 0.07870993, 0.09362339, 0.07208172,
        0.12593589, 0.13339262, 0.12096473, 0.12924999, 0.12924999,
        0.12593589, 0.11267948, 0.08119551, 0.0679391 , 0.06131089,
        0.03645512, 0.03396955, 0.02237019, 0.01159936, 0.00911378,
        0.00745673, 0.00414263, 0.00082853, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.00082853]),
 array([-10.63301471, -10.02953303,  -9.42605135,  -8.82256967,
         -8.21908799,  -7.61560631,  -7.01212463,  -6.40864295,
         -5.80516127,  -5.20167959,  -4.59819791,  -3.99471623,
         -3.39123455,  -2.78775287,  -2.18427119,  -1.58078951,
         -0.97730783,  -0.37382615,   0.22965553,   0.83313721,
          1.43661889,   2.04010057,   2.64358225,   3.24706393,
          3.85054561,   4.45402729,   5.05750897,   5.66099065,
      

In [11]:
def function(a):
    list = np.arange(10)
    i = np.abs(list-a).argmin()
    return list[i]

In [12]:
function(7.193)

7

In [13]:
list = np.arange(10)

In [14]:
list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.abs(list-7.193)

array([7.193, 6.193, 5.193, 4.193, 3.193, 2.193, 1.193, 0.193, 0.807,
       1.807])

In [19]:
a = np.random.randn(3, 4, 1)
b = np.random.rand(3, 1, 2)
c = np.random.randn(3, 1, 1)
d = c + a*b
d.shape

(3, 4, 2)