Exploring Numpy Scalar Types
https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.scalars.html
<img src="https://docs.scipy.org/doc/numpy-1.14.0/_images/dtype-hierarchy.png">

In [2]:
import numpy as np

In [1]:
a = 5
b = 7.5
print( type(a) )
print( type(b) )
print(a + b)
print(a - b)
print(a * b)
print(a / b)

<class 'int'>
<class 'float'>
12.5
-2.5
37.5
0.6666666666666666


In [18]:
isinstance(1, np.unsignedinteger)

False

In [21]:
# Declaring Vectors

x = [1, 2, 3]
y = [4, 5, 6]

print(type(x))

# This does'nt give the vector addition.
print(x + y)

# Vector addition using Numpy

z = np.add(x, y)
print(z)
print(type(z))

# Vector Cross Product
mul = np.cross(x, y)
print(mul)

<class 'list'>
[1, 2, 3, 4, 5, 6]
[5 7 9]
<class 'numpy.ndarray'>
[-3  6 -3]


In [23]:
x = np.matrix([[1,2],[2,3]])
x



matrix([[1, 2],
        [2, 3]])

In [24]:
a = x.mean(0)
a

matrix([[1.5, 2.5]])

In [27]:
z = x.mean(1)
z

matrix([[1.5],
        [2.5]])

In [28]:
z.shape

(2, 1)

In [29]:
y = x - z

In [30]:
print(type(z))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [31]:
import numpy as np

x = np.matrix([[1, 2], [4, 3]])

sum = x.sum()
print(sum)
# Output: 10

10


In [32]:
import numpy as np

x = np.matrix([[1, 2], [4, 3]])
y = np.matrix([[3, 4], [3, 10]])

print(x.shape)
# (2, 2)
print(y.shape)
# (2, 2)

m_sum = np.add(x, y)
print(m_sum)
print(m_sum.shape)
"""
Output : 
[[ 4  6]
 [ 7 13]]
(2, 2)
"""

(2, 2)
(2, 2)
[[ 4  6]
 [ 7 13]]
(2, 2)


'\nOutput : \n[[ 4  6]\n [ 7 13]]\n(2, 2)\n'

In [33]:
##Adds the given scalar to all the elements in the given matrix.
x = np.matrix([[1, 2], [4, 3]])
s_sum = x + 1
print(s_sum)
"""
Output:
[[2 3]
 [5 4]]
"""

[[2 3]
 [5 4]]


'\nOutput:\n[[2 3]\n [5 4]]\n'

In [34]:
# Matrix Scalar Multiplication

x = np.matrix([[1, 2], [4, 3]])
s_mul = x * 3
print(s_mul)
"""
[[ 3  6]
 [12  9]]
"""

[[ 3  6]
 [12  9]]


'\n[[ 3  6]\n [12  9]]\n'

In [35]:
# Matrix Multiplication

a = [[1, 0], [0, 1]]
b = [1, 2]
np.matmul(a, b)
# Output: array([1, 2])

complex_mul = np.matmul([2j, 3j], [2j, 3j])
print(complex_mul)
# Output: (-13+0j)

(-13+0j)


In [38]:

# Matrix Transpose

a = np.array([[1, 2], [3, 4]])
print(a)
"""
[[1 2]
 [3 4]]
"""
a.transpose()
print(a)
"""
array([[1, 3],
       [2, 4]])
"""

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


'\narray([[1, 3],\n       [2, 4]])\n'